spring.application.name=bharatcart-backend

server.port=8080

jwt.secret=my-super-secure-jwt-secret-key-for-bharatcart-2026-very-strong-key

spring.datasource.url=jdbc:postgresql://localhost:5432/bharatcartdb
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Multipart File Upload Limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
